<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HarshvadhansMBP" failures="2" tests="4" name="Test" time="1.083" errors="0" timestamp="2023-12-03T00:18:53 EST">
  <testcase classname="com.Listeners.NewTest" name="testmethod1" time="0.011"/>
  <testcase classname="com.Listeners.NewTest" name="testmethod2" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.Listeners.NewTest.testmethod2(NewTest.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testmethod2 -->
  <testcase classname="com.Listeners.NewTest" name="testmethod4" time="1.01">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.Listeners.NewTest.testmethod4() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.Listeners.NewTest.testmethod4() didn't finish within the time-out 1000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testmethod4 -->
  <testcase classname="com.Listeners.NewTest" name="testmethod3" time="0.0">
    <skipped/>
  </testcase> <!-- testmethod3 -->
</testsuite> <!-- Test -->
